### ISSUE TITLE
Errors. Errors everywhere.

### ISSUE THREAD

**Issue by dannye** [luckytyphlosion/pokeyellow#1]
This doesn't even come close to building anything. I know of course it isn't going to build a real Yellow, but you have introduced so many bugs and typos that this is a nightmare for me to go behind you and fix your mess. This should be redone from the start.

**Comment by luckytyphlosion** [comment]
Can you give examples of some of the bugs/typos I have introduced?

**Comment by dannye** [comment]
https://github.com/luckytyphlosion/pokeyellow/blob/master/home.asm#L168
https://github.com/luckytyphlosion/pokeyellow/blob/master/home/copy2.asm#L17
https://github.com/luckytyphlosion/pokeyellow/blob/master/home/copy2.asm#L21
https://github.com/luckytyphlosion/pokeyellow/blob/master/home/copy2.asm#L137
https://github.com/luckytyphlosion/pokeyellow/blob/master/home/copy2.asm#L140
https://github.com/luckytyphlosion/pokeyellow/blob/master/home/copy2.asm#L141
https://github.com/luckytyphlosion/pokeyellow/blob/master/home/copy2.asm#L143
https://github.com/luckytyphlosion/pokeyellow/blob/master/home/overworld.asm#L290
https://github.com/luckytyphlosion/pokeyellow/blob/master/home/overworld.asm#L641
https://github.com/luckytyphlosion/pokeyellow/blob/master/macros.asm#L77
https://github.com/luckytyphlosion/pokeyellow/blob/master/main.asm#L22
https://github.com/luckytyphlosion/pokeyellow/blob/master/main.asm#L2035
https://github.com/luckytyphlosion/pokeyellow/blob/master/main.asm#L2037
https://github.com/luckytyphlosion/pokeyellow/blob/master/main.asm#L4861

These mistakes consist of multiple identical global labels, references to labels that don't exist, references to files that don't exist, opcodes that don't exist, labels that have invalid symbols, and a macro that doesn't have an ENDM.

In addition to these, there are many other references to labels that don't exist in home/overworld.asm but I'm not going to list them all. That file is seriously messed up, and the worst part is that I can't trace your changes because your text editor changed the EOL encoding of many files and ruined the commit:
https://github.com/luckytyphlosion/pokeyellow/commit/b5f5a16f43ef62680f09666073f07911306e1561

**Comment by luckytyphlosion** [comment]
Fixed the EOL encoding and merged with your repo.

Most of the labels/references that don't exist are because I haven't gotten to fixing/adding those all (e.g. FarCopyData2 is completely removed in Yellow, so it would require a lot time fixing functions that have used the function in pokered)

The other bugs you've mentioned were completely on my fault, so I'll be sure to take caution when editing.

**Comment by dannye** [comment]
Dude. You don't proofread anything you do.

https://github.com/luckytyphlosion/pokeyellow/blame/master/constants/type_constants.asm#L16

**Comment by luckytyphlosion** [comment]
pokeyellow now builds to baserom, closing issue.
